# Gunakan Java JDK 17
FROM eclipse-temurin:17-jdk

# Set direktori kerja di container
WORKDIR /app

# Copy file .jar hasil build
COPY target/*.jar app.jar

# Expose port default Spring Boot
EXPOSE 8080

# Jalankan Spring Boot
ENTRYPOINT ["java","-jar","/app/app.jar"]
