# Stage 1: Build JAR
FROM eclipse-temurin:17-jdk AS build

WORKDIR /app

# Copy semua file project
COPY . .

# Build jar menggunakan maven wrapper (skip tests)
RUN ./mvnw clean package -DskipTests

# Stage 2: Run
FROM eclipse-temurin:17-jdk

WORKDIR /app

# Copy hasil build dari stage pertama
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/app.jar"]
