# Stage 1: Build JAR
FROM eclipse-temurin:17-jdk AS build

WORKDIR /app
COPY . .

# Pastikan mvnw bisa dieksekusi
RUN chmod +x mvnw

# Build jar menggunakan Maven wrapper (skip tests)
RUN ./mvnw clean package -DskipTests

# Stage 2: Run JAR
FROM eclipse-temurin:17-jdk
WORKDIR /app

# Copy hasil build dari stage pertama
COPY --from=build /app/target/*.jar app.jar

# Expose port untuk Spring Boot
EXPOSE 8080

# Jalankan aplikasi
ENTRYPOINT ["java","-jar","/app/app.jar"]
